service: jira-analytics-services

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    DYNAMODB_TABLE: MetricsHistory
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:637423205741:table/MetricsHistory"

functions:
  analyzeTickets:
    name: jira-analyze-ticket
    handler: index.handler

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.github/**'
    - '!*.test.js'
