service: jira-analytics-services

custom:
  functionName: jira-analyze-ticket
  layerName: jira-sns-dependencies

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: MetricsHistory
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:637423205741:table/MetricsHistory"

functions:
  analyzeTickets:
    name: ${self:custom.functionName}
    handler: index.handler
    layers:
      - !Ref JiraSNSDependenciesLambdaLayer

resources:
  Resources:
    JiraSNSDependenciesLambdaLayer:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: ${self:custom.layerName}
        Description: Dependencies for Jira SNS integration
        CompatibleRuntimes:
          - nodejs18.x
        # This resource definition won't create a new layer if we're using the reference-only workflow

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.github/**'
    - '!*.test.js'